name: SonarQube Docker Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Start SonarQube Server
        run: |
          docker run -d --name sonarqube -p 9000:9000 -v ${{ github.workspace }}:/usr/src -w /usr/src sonarqube:community

      - name: Wait for SonarQube to be ready
        run: sleep 20

      - name: SonarQube Analysis
        run: |
          mvn clean verify sonar:sonar \
          -Dsonar.projectKey=my-project \
          -Dsonar.host.url=http://localhost:9000 \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Stop SonarQube
        run: docker stop sonarqube
