name: Flutter CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # 2. Set up Flutter environment
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5' # Replace with your required Flutter version

      # 3. Run `flutter pub get`
      - name: Install dependencies
        run: flutter pub get

      # 4. Optionally run Flutter tests
      - name: Run Flutter Tests
        run: flutter test
